# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:53
from __future__ import unicode_literals

from django.db import migrations

def load_applications_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'application')

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        ('oauth2_provider', '0004_auto_20160525_1623'),
    ]

    operations = [
        migrations.RunPython(load_applications_from_fixture),
    ]
