# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alarm_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Sensor'),
            preserve_default=False,
        ),
    ]
