# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alarm_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='forced_lifesaver',
            field=models.BooleanField(default=False),
        ),
    ]
