# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20170301_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('MMTCode', models.CharField(max_length=255)),
                ('serial_tag', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
