# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='active',
            new_name='handled',
        ),
        migrations.AlterField(
            model_name='structureaffiliation',
            name='mymedtag_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='structuremembership',
            name='mymedtag_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='structureaffiliation',
            unique_together=set([('user', 'structure')]),
        ),
        migrations.AlterUniqueTogether(
            name='structuremembership',
            unique_together=set([('user', 'structure')]),
        ),
    ]
