# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20170302_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
