# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20170303_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, upload_to=b'')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='structureaffiliation',
            name='mymedtag_code',
        ),
        migrations.RemoveField(
            model_name='structuremembership',
            name='mymedtag_code',
        ),
        migrations.AddField(
            model_name='mymedtag',
            name='structure_affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.StructureAffiliation'),
        ),
        migrations.AddField(
            model_name='mymedtag',
            name='structure_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.StructureMembership'),
        ),
    ]
