# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_mymedtag_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Dossier'),
        ),
        migrations.AddField(
            model_name='therapy',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Dossier'),
        ),
    ]
