# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20170323_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller', to=settings.AUTH_USER_MODEL),
        ),
    ]
