# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20170324_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleaffiliation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
