# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_circleaffiliation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleaffiliation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='circleaffiliation',
            unique_together=set([('circle', 'email')]),
        ),
    ]
