# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20170330_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleaffiliation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
