# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_userprofile_lifesaver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='circle',
            field=models.ManyToManyField(blank=True, to='backend.Circle'),
        ),
    ]
