# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20170428_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
