# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20170530_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
