# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20170530_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lifesaver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.AttributeValue'),
        ),
    ]
