# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20170530_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('action_type', models.CharField(choices=[('sms', 'Sms'), ('call', 'Call'), ('email', 'Email'), ('post', 'Post')], max_length=255)),
                ('affiliation', models.ManyToManyField(to='backend.StructureAffiliation')),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Circle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.TimeField()),
                ('handled', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ActionCOC')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.StructureAffiliation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SerialCOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('duration', models.IntegerField(default=0)),
                ('serial', models.CharField(max_length=255)),
                ('valid', models.BooleanField(default=True)),
                ('start_date_validation', models.DateField()),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.StructureAffiliation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='structure',
            name='code_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
