# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_serialcoc_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialcoc',
            name='start_date_validation',
            field=models.DateField(blank=True),
        ),
    ]
