# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_auto_20170626_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistancerequest',
            name='action',
        ),
        migrations.RemoveField(
            model_name='assistancerequest',
            name='affiliation',
        ),
        migrations.DeleteModel(
            name='AssistanceRequest',
        ),
    ]
