# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 12:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20170626_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateTimeField(blank=True)),
                ('handled', models.BooleanField(default=False)),
                ('latlng', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ActionCOC')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.StructureAffiliation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
