# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_remove_assistancerequest_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='structure',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='backend.Structure'),
            preserve_default=False,
        ),
    ]
