# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_assistancerequest_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistancecaller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistancehandler', to=settings.AUTH_USER_MODEL),
        ),
    ]
