# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20170626_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistancerequest',
            name='caller',
        ),
    ]
