# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_remove_assistancerequest_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.StructureAffiliation'),
        ),
    ]
