# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 16:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_assistancerequest_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='latlng',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
