# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_auto_20170626_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncoc',
            name='action_type',
            field=models.CharField(choices=[('sms', 'Sms'), ('call', 'Call'), ('email', 'Email'), ('circle', 'Gruppi')], max_length=255),
        ),
    ]
