# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_auto_20170627_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncoc',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
