# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_auto_20170627_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Post'),
        ),
    ]
