# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_auto_20170705_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='datatype',
            field=models.CharField(choices=[('text', 'Text'), ('boolean', 'Boolean'), ('number', 'Number'), ('date_with_checkbox', 'Date with Checkbox'), ('label', 'Label'), ('enum', 'Choices')], max_length=255),
        ),
    ]
