# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_auto_20170906_1640'),
    ]

    operations = [
    ]
