# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-29 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_auto_20170908_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
