# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-24 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_structure_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
