# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 22:39
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_registration', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name=b'first_registration')),
                ('last_registration', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name=b'last_registration')),
                ('token', models.TextField(blank=True)),
                ('app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('app_version', models.CharField(blank=True, max_length=32, null=True)),
                ('os_type', models.CharField(blank=True, max_length=32, null=True)),
                ('os_version', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('locale', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name=b'created')),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('body', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('title_loc_key', models.CharField(blank=True, max_length=64, null=True)),
                ('body_loc_key', models.CharField(blank=True, max_length=64, null=True)),
                ('body_loc_arg', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64, null=True), size=None)),
                ('tokens', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('data_message', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
